using Dle.Domain.Routing;

namespace Dle.ContractTests.Routing;

/// <summary>
/// The published schema of <c>links.routing_rules</c> (§B.5.4), and its agreement with the validator
/// the control plane actually enforces at write time.
/// </summary>
/// <remarks>
/// <para>
/// The rule set is the one part of a link that a customer authors as a document rather than through a
/// form: it is edited in the admin UI, generated by scripts, and templated across campaigns. That
/// makes it a published contract, and §B.5.4 says so — "validácia: JSON Schema, kontrolovaná pri
/// zápise… Pravidlá bez default sa neuložia".
/// </para>
/// <para>
/// Two things are therefore asserted. The schema must accept the specification's own example, because
/// a schema that rejects the documentation is worse than no schema. And the schema and
/// <see cref="RoutingRuleValidator"/> must agree on the one rule that matters, the mandatory default:
/// a document the schema accepts and the server then refuses is a contract that lies to the client
/// that generated it.
/// </para>
/// </remarks>
public sealed class RoutingRulesSchemaTests
{
    /// <summary>The committed schema.</summary>
    public const string SchemaFileName = "routing-rules.schema.json";

    /// <summary>
    /// The rule set printed in §B.5.4, transcribed verbatim.
    /// </summary>
    /// <remarks>
    /// Verbatim on purpose, ellipses and all resolved but nothing renamed. If this fails to validate,
    /// either the schema is wrong or the documentation is, and both are bugs worth stopping for.
    /// </remarks>
    public const string SpecificationExample =
        """
        [
          {
            "id": "r1",
            "when": {
              "platform": ["ios"],
              "os_version": { "gte": "17.0" },
              "country": ["SK", "CZ"]
            },
            "then": {
              "action": "app_or_store",
              "deeplink_path": "/promo/jesen",
              "store_url": "https://apps.apple.com/app/id123456789?pt=1234&ct=jesen26&mt=8",
              "interstitial": "auto"
            }
          },
          {
            "id": "r2",
            "when": { "platform": ["android"] },
            "then": {
              "action": "app_or_store",
              "deeplink_path": "/promo/jesen",
              "store_url": "https://play.google.com/store/apps/details?id=com.example",
              "referrer_template": "dl_cid={click_id}&utm_source={utm_source}&utm_campaign={utm_campaign}"
            }
          },
          {
            "id": "default",
            "then": { "action": "web", "url": "https://www.example.com/promo/jesen" }
          }
        ]
        """;

    private static readonly JsonSchemaValidator Schema =
        JsonSchemaValidator.Parse(RepositoryLayout.ReadContract(SchemaFileName));

    [Fact]
    [Trait("TestCase", "TC-105")]
    public void Schema_AcceptsTheExampleFromSectionB54()
    {
        IReadOnlyList<SchemaViolation> violations = Schema.ValidateJson(SpecificationExample);

        Assert.True(
            violations.Count == 0,
            "The committed schema rejects the rule set printed in §B.5.4:" + Environment.NewLine
                + JsonSchemaValidator.Describe(violations));
    }

    [Fact]
    [Trait("TestCase", "TC-105")]
    public void Schema_RejectsARuleSetWithNoDefaultRule()
    {
        // Every rule carries a "when", so a client matching none of them would fall off the end.
        const string withoutDefault =
            """
            [
              { "id": "r1", "when": { "platform": ["ios"] }, "then": { "action": "web", "url": "https://example.com/i" } },
              { "id": "r2", "when": { "platform": ["android"] }, "then": { "action": "web", "url": "https://example.com/a" } }
            ]
            """;

        IReadOnlyList<SchemaViolation> violations = Schema.ValidateJson(withoutDefault);

        Assert.Contains(violations, violation => violation.Keyword == "contains");
    }

    [Fact]
    [Trait("TestCase", "TC-105")]
    public void Schema_RejectsMoreThanOneDefaultRule()
    {
        // Two rules without "when" means the second can never be reached, which is a rule set whose
        // author believes something the engine does not.
        const string twoDefaults =
            """
            [
              { "id": "a", "then": { "action": "web", "url": "https://example.com/a" } },
              { "id": "b", "then": { "action": "web", "url": "https://example.com/b" } }
            ]
            """;

        IReadOnlyList<SchemaViolation> violations = Schema.ValidateJson(twoDefaults);

        Assert.Contains(violations, violation => violation.Keyword == "maxContains");
    }

    [Fact]
    [Trait("TestCase", "TC-105")]
    public void Validator_AndSchema_AgreeThatADefaultRuleIsMandatory()
    {
        // The schema is what a client generates against; the validator is what the server enforces.
        // If they disagree, the client is handed a document it believes is valid and the API refuses
        // it, which is the worst of both.
        RoutingRule[] withoutDefault =
        [
            new RoutingRule
            {
                Id = "r1",
                When = new RuleCondition { Platform = ["ios"] },
                Then = new RuleAction { Action = RoutingActionKind.Web, Url = "https://example.com/i" },
            },
        ];

        Assert.False(RoutingRuleValidator.IsValid(withoutDefault));

        Assert.Contains(
            RoutingRuleValidator.Validate(withoutDefault),
            error => error.Message.Contains("default rule", StringComparison.Ordinal));
    }

    [Fact]
    public void Validator_AcceptsTheExampleFromSectionB54()
    {
        // The same document, through the product's own deserializer and its own write-time validation.
        // Together with the schema test above this is what makes the schema a contract rather than a
        // second opinion: one document, accepted by both.
        RoutingRule[]? rules = JsonSerializer.Deserialize<RoutingRule[]>(SpecificationExample, DleJson.Default);

        Assert.NotNull(rules);
        Assert.Equal(3, rules.Length);

        IReadOnlyList<RoutingValidationError> errors = RoutingRuleValidator.Validate(rules);

        Assert.True(
            errors.Count == 0,
            "The write-time validator rejects the rule set printed in §B.5.4: "
                + string.Join("; ", errors.Select(error => error.Path + " " + error.Message)));
    }

    [Fact]
    public void Schema_RejectsANonHttpTarget()
    {
        // T-01 and TC-161 at the document level. The server refuses these too, but a schema that
        // accepts them means every editor and generator will happily produce one.
        const string javascriptTarget =
            """
            [ { "id": "default", "then": { "action": "web", "url": "javascript:alert(1)" } } ]
            """;

        IReadOnlyList<SchemaViolation> violations = Schema.ValidateJson(javascriptTarget);

        Assert.Contains(violations, violation => violation.Keyword == "pattern");
    }

    [Fact]
    public void Schema_RejectsAnUnknownAction()
    {
        const string unknownAction =
            """
            [ { "id": "default", "then": { "action": "redirect_all", "url": "https://example.com" } } ]
            """;

        Assert.Contains(Schema.ValidateJson(unknownAction), violation => violation.Keyword == "enum");
    }

    [Fact]
    public void Schema_RejectsAnUndeclaredPredicate()
    {
        // Closed by construction. An unknown predicate that is silently ignored is a rule that looks
        // narrower than it is, which in a campaign means traffic going somewhere nobody intended.
        const string unknownPredicate =
            """
            [
              { "id": "r1", "when": { "is_vip": true }, "then": { "action": "web", "url": "https://example.com/v" } },
              { "id": "default", "then": { "action": "web", "url": "https://example.com" } }
            ]
            """;

        Assert.Contains(
            Schema.ValidateJson(unknownPredicate),
            violation => violation.Keyword == "additionalProperties");
    }

    [Fact]
    public void Schema_RejectsARuleSetLargerThanTheEvaluatorAccepts()
    {
        // The bound in the schema is the bound in RoutingRuleValidator.MaxRules; a schema that let a
        // client generate a longer set would produce a document the server always refuses.
        Assert.Equal(
            RoutingRuleValidator.MaxRules,
            JsonNode.Parse(RepositoryLayout.ReadContract(SchemaFileName))!["maxItems"]!.GetValue<int>());
    }

    [Fact]
    [Trait("Threat", "T-12")]
    public void Schema_IsADocumentWithoutPolymorphism()
    {
        // T-12: the deserialization surface must be a closed set of named members. A schema keyword
        // that selects a type at read time is exactly what §E.2.2 forbids here, so the committed
        // document is asserted to contain none.
        string schema = RepositoryLayout.ReadContract(SchemaFileName);

        Assert.DoesNotContain("\"$dynamicRef\"", schema, StringComparison.Ordinal);
        Assert.DoesNotContain("\"discriminator\"", schema, StringComparison.Ordinal);
    }
}
