// <auto-generated />
using System;
using System.Collections.Generic;
using Dle.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dle.Persistence.Migrations
{
    [DbContext(typeof(DleDbContext))]
    [Migration("20260904160723_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dle.Domain.Entities.AbuseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<long>("LinkId")
                        .HasColumnType("bigint")
                        .HasColumnName("link_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<byte[]>("ReporterEmailHash")
                        .HasColumnType("bytea")
                        .HasColumnName("reporter_email_hash");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("new")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_abuse_reports");

                    b.HasIndex("LinkId")
                        .HasDatabaseName("ix_abuse_reports_link");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_abuse_reports_queue");

                    b.ToTable("abuse_reports", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.PrimitiveCollection<List<string>>("Scopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("Prefix")
                        .IsUnique()
                        .HasDatabaseName("uq_api_keys_prefix");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_api_keys_tenant");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<string>("AppClipBundleId")
                        .HasColumnType("text")
                        .HasColumnName("appclip_bundle_id");

                    b.Property<string>("BundleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bundle_id");

                    b.PrimitiveCollection<List<string>>("CertFingerprints")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("cert_fingerprints")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomScheme")
                        .HasColumnType("text")
                        .HasColumnName("custom_scheme");

                    b.Property<string>("MinAppVersion")
                        .HasColumnType("text")
                        .HasColumnName("min_app_version");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.PrimitiveCollection<List<string>>("PlaySigningFingerprints")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("play_signing_fingerprints")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("StoreId")
                        .HasColumnType("text")
                        .HasColumnName("store_id");

                    b.Property<string>("StoreUrl")
                        .HasColumnType("text")
                        .HasColumnName("store_url");

                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_apps");

                    b.HasIndex("TenantId", "Platform", "BundleId")
                        .IsUnique()
                        .HasDatabaseName("uq_apps_tenant_platform_bundle");

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.AppDomain", b =>
                {
                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.HasKey("AppId", "DomainId")
                        .HasName("pk_app_domains");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_app_domains_domain");

                    b.ToTable("app_domains", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.AttributionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<string>("ClickId")
                        .HasColumnType("text")
                        .HasColumnName("click_id");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("confidence");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<long?>("LinkId")
                        .HasColumnType("bigint")
                        .HasColumnName("link_id");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_type");

                    b.Property<DateTimeOffset>("MatchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("matched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("WindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("window_seconds");

                    b.HasKey("Id")
                        .HasName("pk_attributions");

                    b.HasIndex("ClickId")
                        .IsUnique()
                        .HasDatabaseName("uq_attributions_click")
                        .HasFilter("click_id IS NOT NULL");

                    b.HasIndex("InstallId")
                        .IsUnique()
                        .HasDatabaseName("uq_attributions_install");

                    b.HasIndex("TenantId", "MatchedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_attributions_tenant_matched");

                    b.ToTable("attributions", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("TenantId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_tenant_occurred");

                    b.HasIndex("TenantId", "SubjectType", "SubjectId")
                        .HasDatabaseName("ix_audit_log_subject");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Utm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("utm")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_campaigns_tenant_name");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.ClaimCodeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<string>("ClickId")
                        .HasColumnType("text")
                        .HasColumnName("click_id");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("LinkId")
                        .HasColumnType("bigint")
                        .HasColumnName("link_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_claim_codes");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_claim_codes_expires");

                    b.HasIndex("TenantId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("uq_claim_codes_tenant_hash");

                    b.ToTable("claim_codes", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.DomainVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<string>("Issues")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("issues")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("RedirectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("redirect_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_domain_verifications");

                    b.HasIndex("DomainId", "Kind", "CheckedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_domain_verifications_domain_kind_checked");

                    b.ToTable("domain_verifications", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.HasKey("TenantId", "Endpoint", "Key")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.Install", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("FirstOpenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_open_at");

                    b.Property<string>("InstallId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("install_id");

                    b.Property<byte[]>("LoginKeyHash")
                        .HasColumnType("bytea")
                        .HasColumnName("login_key_hash");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("RawReferrer")
                        .HasColumnType("text")
                        .HasColumnName("raw_referrer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_installs");

                    b.HasIndex("AppId", "InstallId")
                        .IsUnique()
                        .HasDatabaseName("uq_installs_app_install");

                    b.HasIndex("TenantId", "LoginKeyHash")
                        .HasDatabaseName("ix_installs_login_key")
                        .HasFilter("login_key_hash IS NOT NULL");

                    b.ToTable("installs", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.Link", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DeeplinkPath")
                        .HasColumnType("text")
                        .HasColumnName("deeplink_path");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("ExpiredUrl")
                        .HasColumnType("text")
                        .HasColumnName("expired_url");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OgMeta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("og_meta")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("QuarantinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quarantined_at");

                    b.Property<string>("RoutingRules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("routing_rules")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_url");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Utm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("utm")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_links");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_links_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("TenantId", "CampaignId")
                        .HasDatabaseName("ix_links_tenant_campaign");

                    b.HasIndex("TenantId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_links_tenant_created");

                    b.HasIndex(new[] { "DomainId", "Slug" }, "ix_links_resolve")
                        .HasDatabaseName("ix_links_resolve");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "DomainId", "Slug" }, "ix_links_resolve"), new[] { "TargetUrl", "DeeplinkPath", "RoutingRules", "OgMeta", "IsActive", "StartsAt", "ExpiresAt", "QuarantinedAt", "TenantId", "Id", "Utm", "Title", "CampaignId", "ExpiredUrl" });

                    b.HasIndex(new[] { "DomainId", "Slug" }, "uq_links_domain_slug")
                        .IsUnique()
                        .HasDatabaseName("uq_links_domain_slug");

                    b.ToTable("links", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.LinkDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<string>("AasaStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("aasa_status");

                    b.Property<string>("AssetlinksStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("assetlinks_status");

                    b.Property<string>("Branding")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("branding")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ConsentModeOverride")
                        .HasColumnType("text")
                        .HasColumnName("consent_mode_override");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultOg")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("default_og")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("host");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TlsStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("tls_status");

                    b.Property<string>("VerificationLog")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("verification_log")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id")
                        .HasName("pk_domains");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("uq_domains_host");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_domains_tenant");

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.LinkVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<string>("ChangeNote")
                        .HasColumnType("text")
                        .HasColumnName("change_note");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<long>("LinkId")
                        .HasColumnType("bigint")
                        .HasColumnName("link_id");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_link_versions");

                    b.HasIndex("LinkId", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_link_versions_link_version");

                    b.ToTable("link_versions", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.SdkKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_prefix");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sdk_keys");

                    b.HasIndex("AppId")
                        .HasDatabaseName("ix_sdk_keys_app");

                    b.HasIndex("KeyPrefix")
                        .IsUnique()
                        .HasDatabaseName("uq_sdk_keys_prefix");

                    b.ToTable("sdk_keys", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.SigningKeyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("algorithm");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<string>("Kid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kid");

                    b.Property<DateTimeOffset?>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<byte[]>("PrivateKeyEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("private_key_encrypted");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_signing_keys");

                    b.HasIndex("Kid")
                        .IsUnique()
                        .HasDatabaseName("uq_signing_keys_kid");

                    b.HasIndex("Purpose", "NotAfter")
                        .HasDatabaseName("ix_signing_keys_purpose_validity");

                    b.HasIndex("TenantId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("uq_signing_keys_current")
                        .HasFilter("is_current");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "Purpose"), false);

                    b.ToTable("signing_keys", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.SlugSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<long>("BlockEnd")
                        .HasColumnType("bigint")
                        .HasColumnName("block_end");

                    b.Property<long>("BlockStart")
                        .HasColumnType("bigint")
                        .HasColumnName("block_start");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text")
                        .HasColumnName("claimed_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_slug_sequences");

                    b.HasIndex("Name", "BlockStart")
                        .IsUnique()
                        .HasDatabaseName("uq_slug_sequences_name_start");

                    b.ToTable("slug_sequences", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<string>("ConsentMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("aggregate_only")
                        .HasColumnName("consent_mode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<int>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_webhook_deliveries");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_webhook_deliveries_due")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("TenantId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_webhook_deliveries_tenant_created");

                    b.ToTable("webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("dle_uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<List<string>>("EventTypes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("event_types")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<byte[]>("SecretEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_encrypted");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_webhook_subscriptions");

                    b.HasIndex("EventTypes")
                        .HasDatabaseName("ix_webhook_subscriptions_event_types");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EventTypes"), "gin");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_webhook_subscriptions_tenant");

                    b.ToTable("webhook_subscriptions", (string)null);
                });

            modelBuilder.Entity("Dle.Domain.Entities.AbuseReport", b =>
                {
                    b.HasOne("Dle.Domain.Entities.Link", null)
                        .WithMany()
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_abuse_reports_link");
                });

            modelBuilder.Entity("Dle.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("Dle.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_tenant");
                });

            modelBuilder.Entity("Dle.Domain.Entities.AppDomain", b =>
                {
                    b.HasOne("Dle.Domain.Entities.App", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_domains_app");

                    b.HasOne("Dle.Domain.Entities.LinkDomain", null)
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_domains_domain");
                });

            modelBuilder.Entity("Dle.Domain.Entities.AttributionRecord", b =>
                {
                    b.HasOne("Dle.Domain.Entities.Install", null)
                        .WithMany()
                        .HasForeignKey("InstallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attributions_install");
                });

            modelBuilder.Entity("Dle.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("Dle.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaigns_tenant");
                });

            modelBuilder.Entity("Dle.Domain.Entities.DomainVerification", b =>
                {
                    b.HasOne("Dle.Domain.Entities.LinkDomain", null)
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_domain_verifications_domain");
                });

            modelBuilder.Entity("Dle.Domain.Entities.Install", b =>
                {
                    b.HasOne("Dle.Domain.Entities.App", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_installs_app");
                });

            modelBuilder.Entity("Dle.Domain.Entities.Link", b =>
                {
                    b.HasOne("Dle.Domain.Entities.LinkDomain", null)
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_links_domain");

                    b.HasOne("Dle.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_links_tenant");
                });

            modelBuilder.Entity("Dle.Domain.Entities.LinkVersion", b =>
                {
                    b.HasOne("Dle.Domain.Entities.Link", null)
                        .WithMany()
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_versions_link");
                });

            modelBuilder.Entity("Dle.Domain.Entities.SdkKey", b =>
                {
                    b.HasOne("Dle.Domain.Entities.App", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sdk_keys_app");
                });

            modelBuilder.Entity("Dle.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("Dle.Domain.Entities.WebhookSubscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_deliveries_subscription");
                });

            modelBuilder.Entity("Dle.Domain.Entities.WebhookSubscription", b =>
                {
                    b.HasOne("Dle.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_subscriptions_tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
