namespace Dle.Domain.Entities;

/// <summary>
/// One installation of a customer application, as reported by the SDK. Maps to <c>installs</c>.
/// </summary>
/// <remarks>
/// The pair of application and install identifier is unique, which is what makes a repeated
/// resolve idempotent: the second call finds the existing row and returns the existing
/// attribution instead of creating a second one (TC-143, FR-188).
/// </remarks>
public class Install
{
    /// <summary>Primary key, a UUIDv7.</summary>
    public Guid Id { get; set; }

    /// <summary>Owning tenant.</summary>
    public Guid TenantId { get; set; }

    /// <summary>Application that was installed.</summary>
    public Guid AppId { get; set; }

    /// <summary>Identifier generated by the SDK, stable for the lifetime of the installation.</summary>
    public string InstallId { get; set; } = string.Empty;

    /// <summary>Instant of the first application open, in UTC.</summary>
    public DateTimeOffset FirstOpenAt { get; set; }

    /// <summary>The Play install referrer exactly as the platform returned it. Kept verbatim so
    /// that a disputed attribution can be re-examined against the original evidence.</summary>
    public string? RawReferrer { get; set; }

    /// <summary>Platform, stored as text: <c>ios</c> or <c>android</c>.</summary>
    public string Platform { get; set; } = string.Empty;

    /// <summary>Application version at first open.</summary>
    public string? AppVersion { get; set; }

    /// <summary>Hash of the account identifier used for login reconciliation (S2). A hash, never
    /// the account identifier itself.</summary>
    public byte[]? LoginKeyHash { get; set; }

    /// <summary>Creation instant, in UTC.</summary>
    public DateTimeOffset CreatedAt { get; set; }
}
