using System.Diagnostics.CodeAnalysis;
using System.Globalization;

using Npgsql;

namespace Dle.IntegrationTests.Infrastructure;

/// <summary>
/// One test's own PostgreSQL database, copied from the migrated template and dropped afterwards.
/// </summary>
/// <remarks>
/// <para>
/// Database per test rather than a transaction per test. A transaction would be cheaper, but three
/// of the things under test cannot happen inside one: <c>CREATE DATABASE</c> semantics aside, the
/// edge and the control plane run in their own hosts with their own connection pools and would
/// never see an uncommitted row; the <c>COPY</c> writer runs on a background thread with a
/// connection of its own; and <c>EXPLAIN (ANALYZE)</c> against a table whose rows are invisible to
/// the planner's statistics measures nothing.
/// </para>
/// <para>
/// The data source is exposed so that a test can read the database back through the same driver the
/// product uses, with the same type mapping — which is the point of asserting on <c>jsonb</c>,
/// <c>citext</c> and <c>inet</c> at all.
/// </para>
/// </remarks>
public sealed class TestDatabase : IAsyncDisposable
{
    private readonly string _adminConnectionString;
    private readonly NpgsqlDataSource _dataSource;
    private bool _disposed;

    private readonly bool _dropOnDispose;

    /// <summary>Creates the handle.</summary>
    /// <param name="name">Database name on the container.</param>
    /// <param name="connectionString">Connection string addressing it.</param>
    /// <param name="adminConnectionString">Connection string addressing the maintenance database.</param>
    /// <param name="dropOnDispose">
    /// Whether the database is dropped when the handle is disposed. False for a database that is a
    /// container's own — the container goes away instead, and dropping the database an admin
    /// connection is made through is not possible anyway.
    /// </param>
    public TestDatabase(
        string name,
        string connectionString,
        string adminConnectionString,
        bool dropOnDispose = true)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        ArgumentException.ThrowIfNullOrWhiteSpace(connectionString);
        ArgumentException.ThrowIfNullOrWhiteSpace(adminConnectionString);

        Name = name;
        ConnectionString = connectionString;
        _adminConnectionString = adminConnectionString;
        _dropOnDispose = dropOnDispose;
        _dataSource = NpgsqlDataSource.Create(connectionString);
    }

    /// <summary>The database name.</summary>
    public string Name { get; }

    /// <summary>Connection string addressing this database.</summary>
    public string ConnectionString { get; }

    /// <summary>A pooled data source over this database.</summary>
    public NpgsqlDataSource DataSource => _dataSource;

    /// <summary>Opens a connection to this database.</summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The open connection.</returns>
    public ValueTask<NpgsqlConnection> OpenAsync(CancellationToken cancellationToken = default) =>
        _dataSource.OpenConnectionAsync(cancellationToken);

    /// <inheritdoc />
    [SuppressMessage(
        "Security",
        "CA2100:Review SQL queries for security vulnerabilities",
        Justification = "DROP DATABASE takes no parameters. The name was generated by "
                        + "DleInfrastructureFixture and never comes from outside the test suite.")]
    public async ValueTask DisposeAsync()
    {
        if (_disposed)
        {
            return;
        }

        _disposed = true;

        await _dataSource.DisposeAsync();

        if (!_dropOnDispose)
        {
            return;
        }

        try
        {
            await using NpgsqlConnection admin = new(_adminConnectionString);
            await admin.OpenAsync();

            await using NpgsqlCommand drop = admin.CreateCommand();

            // WITH (FORCE) terminates whatever is still connected. A host that has not finished
            // shutting down must not be able to keep a test database alive for the rest of the run.
            drop.CommandText = string.Create(
                CultureInfo.InvariantCulture,
                $"DROP DATABASE IF EXISTS \"{Name}\" WITH (FORCE)");

            await drop.ExecuteNonQueryAsync();
        }
#pragma warning disable CA1031 // Do not catch general exception types
        // Cleanup must never turn a passing test red. The container is torn down at the end of the
        // assembly in any case, so a database that outlives its test costs nothing.
        catch (Exception)
#pragma warning restore CA1031
        {
            // Deliberately ignored; see above.
        }
    }
}
